server-name=CMZ Server
game-name=CastleMinerZSteam
network-version=4

server-ip=0.0.0.0
server-port=61903
max-players=8

game-path=C:\Program Files (x86)\Steam\steamapps\common\CastleMiner Z

save-owner-steam-id=76561198296842857
world-guid=b8c81243-b6ac-48fe-a782-1e2dc5a44d17

view-distance-chunks=8
tick-rate-hz=60

game-mode=1
pvp-state=0
difficulty=1